# Generated by Django 3.2.5 on 2022-07-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseno', models.IntegerField(max_length=5)),
                ('coursename', models.CharField(max_length=30)),
                ('duration', models.IntegerField(max_length=5)),
                ('fees', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
