# Generated by Django 3.2.5 on 2022-07-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220719_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='courseno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
