# Generated by Django 3.2.5 on 2022-07-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220719_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchno', models.IntegerField(primary_key=True, serialize=False)),
                ('batchname', models.CharField(max_length=30)),
                ('batchtime', models.IntegerField()),
                ('maxstudents', models.IntegerField()),
                ('currentstu', models.IntegerField()),
            ],
            options={
                'db_table': 'batch',
            },
        ),
    ]
