# Generated by Django 3.2.5 on 2022-07-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='admindata',
            fields=[
                ('adminid', models.IntegerField(primary_key=True, serialize=False)),
                ('adminname', models.CharField(max_length=30)),
                ('adminpass', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
