# Generated by Django 3.2.5 on 2022-07-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_admindata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admindata',
            table='admindata',
        ),
    ]
