# Generated by Django 3.2.5 on 2022-07-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_admindata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admindata',
            table='Admindata',
        ),
    ]
