# Generated by Django 3.2.5 on 2022-07-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_admindata_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admindata',
            new_name='Admin',
        ),
        migrations.AlterModelTable(
            name='admin',
            table='Admin',
        ),
    ]
