# Generated by Django 3.2.5 on 2022-07-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20220725_1600'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='batch',
            table='Batch',
        ),
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
    ]
