# Generated by Django 3.2.5 on 2022-07-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20220725_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('queryid', models.IntegerField(primary_key=True, serialize=False)),
                ('qname', models.CharField(max_length=30)),
                ('qemail', models.CharField(max_length=30)),
                ('qphone', models.IntegerField()),
                ('query', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Query',
            },
        ),
    ]
